config/routes.rb
Fashionfeed::Application.routes.draw do
  resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :image_url, :designer, :colspan, :event
  self.per_page = 40
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.paginate(:page => params[:page]).order('id ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fashionfeed</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <meta name = "viewport" content = "width=1440">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %><br />
    <%= f.label :designer %><br />
    <%= f.text_field :designer %><br />
        <%= f.label :colspan %><br />
    <%= f.text_field :colspan %><br />

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Front Row</h1>

<div id="overlay" >
<div id="bigimage-container">

<div id="bigimage-text">
<p id="bigimage-caption"></p><p id="bigimage-event"></p>
<p> <a href="#" id="bigimage-editlink">[Edit]</a></p>
</div>
</div>

<div id="overlay-bg" onclick="FASHIONFEED.hideOverlay();"></div>

</div>
<div id="container">

<% @photos.each do |photo| %>
<% 
  randomRot = 0
#   randomRot = rand(-5...5)
widths = [80,180,280,380]  
  randomWidth = widths[photo.colspan]

# randomWidth = 40
%>
<div class="fashion-img-container item" style="transform:rotate(<%= randomRot %>deg) -ms-transform: rotate(<%= randomRot %>deg); /* IE 9 */ -webkit-transform: rotate(<%= randomRot %>deg); /* Safari and Chrome */ ">
 <a href="#<%= photo.id %>" onclick="FASHIONFEED.showOverlay('<%= photo.id %>')">
 <%= 
  image_tag(photo.image_url, :class => "fashion", :width => randomWidth)
# image_tag(photo.image_url, :class => "fashion")
  %>
</a>
    <div class="elementui">
      <%= link_to 'Show', photo %>
    <%= link_to 'Edit', edit_photo_path(photo) %>
    <%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></div>
</div>
<% end %>
</div>

<%= will_paginate(@photos) %>



<br />
<!--
<%= link_to 'New Photo', new_photo_path %>

-->

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image url:</b>
  <%= @photo.image_url %>
</p>
<p>
  <b>Designer:</b>
  <%= @photo.designer %>
</p>
<p>
  <b>Column Span:</b>
  <%= @photo.colspan %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>